//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34011
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager2 {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    partial class TextPad {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextPad() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manager2.TextPad", typeof(TextPad).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point menuStrip1_Location {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=928, Height=24}.
        /// </summary>
        public static System.Drawing.Size menuStrip1_Size {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 2.
        /// </summary>
        public static int menuStrip1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на menuStrip1.
        /// </summary>
        public static string menuStrip1_Text {
            get {
                return ResourceManager.GetString("menuStrip1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=368,Y=19}.
        /// </summary>
        public static System.Drawing.Point menuStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=17,Y=17}.
        /// </summary>
        public static System.Drawing.Point openFileDialog1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("openFileDialog1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=12,Y=34}.
        /// </summary>
        public static System.Drawing.Point richTextBox1_Location {
            get {
                object obj = ResourceManager.GetObject("richTextBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=904, Height=353}.
        /// </summary>
        public static System.Drawing.Size richTextBox1_Size {
            get {
                object obj = ResourceManager.GetObject("richTextBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 1.
        /// </summary>
        public static int richTextBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("richTextBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string richTextBox1_Text {
            get {
                return ResourceManager.GetString("richTextBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=157,Y=17}.
        /// </summary>
        public static System.Drawing.Point saveFileDialog1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("saveFileDialog1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=235, Height=22}.
        /// </summary>
        public static System.Drawing.Size вирізатиToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("вирізатиToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вирізати.
        /// </summary>
        public static string вирізатиToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("вирізатиToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=235, Height=22}.
        /// </summary>
        public static System.Drawing.Size вставитиToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("вставитиToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставити.
        /// </summary>
        public static string вставитиToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("вставитиToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=235, Height=22}.
        /// </summary>
        public static System.Drawing.Size замінитиПослідовністьЛітерToolStripMenuItem1_Size {
            get {
                object obj = ResourceManager.GetObject("замінитиПослідовністьЛітерToolStripMenuItem1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Замінити послідовність літер.
        /// </summary>
        public static string замінитиПослідовністьЛітерToolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("замінитиПослідовністьЛітерToolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=142, Height=22}.
        /// </summary>
        public static System.Drawing.Size зберегтиToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("зберегтиToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зберегти.
        /// </summary>
        public static string зберегтиToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("зберегтиToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=235, Height=22}.
        /// </summary>
        public static System.Drawing.Size знайтиСхожіСловаToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("знайтиСхожіСловаToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Знайти схожі слова.
        /// </summary>
        public static string знайтиСхожіСловаToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("знайтиСхожіСловаToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=235, Height=22}.
        /// </summary>
        public static System.Drawing.Size копіюватиToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("копіюватиToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копіювати.
        /// </summary>
        public static string копіюватиToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("копіюватиToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=142, Height=22}.
        /// </summary>
        public static System.Drawing.Size новийФайлToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("новийФайлToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новий файл.
        /// </summary>
        public static string новийФайлToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("новийФайлToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=49, Height=20}.
        /// </summary>
        public static System.Drawing.Size текстToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("текстToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст.
        /// </summary>
        public static string текстToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("текстToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=48, Height=20}.
        /// </summary>
        public static System.Drawing.Size файлToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("файлToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл.
        /// </summary>
        public static string файлToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("файлToolStripMenuItem.Text", resourceCulture);
            }
        }
    }
}
